name: "Static Analysis"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Check conventional commits
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: wagoid/commitlint-github-action@v6
