name: "juju-tf-upgrader Unit Tests"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit-tests:
    name: Run juju-tf-upgrader unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "juju-tf-upgrader/go.mod"
      - run: cd juju-tf-upgrader && go test -v 
